### ISSUE TITLE
gomobile: unsupported basic type: uint64

### ISSUE THREAD

**Issue by nicholaswhittle** [lastochkanetwork/EasyPGP#1]
Trying to bind using the commands given..

> gomobile bind -target=ios -o EasyPGP.framework  github.com/encryptedtimeline/easypgp

**Comment by 54a0ff4842ec9** [comment]
@nicwhitts you'll need to manually patch gomobile to support it. I've added exact patch to readme. I wonder if @crawshaw is going to fix this.

**Comment by nicholaswhittle** [comment]
Am i missing something obvious, but i have changed the patch in 
go/src/golang.org/x/mobile/bind/gen.go?
And I'm still getting the same error. 
Even before init

**Comment by 54a0ff4842ec9** [comment]
@nicwhitts But did you recompile `gomobile` binary with the patch? You might want to do `go install golang.org/x/mobile/cmd/gomobile`

**Comment by nicholaswhittle** [comment]
I knew it would be simple, I'm new to go
That did the trick!
